### ISSUE TITLE
Park Images

### ISSUE THREAD

**Issue by ellenbmorrison** [csloz/web-dev-uol-pt3#5]
I am not sure if we wanted to keep the disney photos or not so I grabbed a few generic stock photos of dinosaurs and roller coasters just in case we wanted to change them. If you want more let me know. 
[Web Dev Theme Park Pics.zip](https://github.com/csloz/web-dev-uol-pt3/files/6673485/Web.Dev.Theme.Park.Pics.zip)

**Comment by csloz** [comment]
You should put these into your repo folder and merge it (unzipped). i.e. in 

assets/images
